language: cpp
sudo: true
dist: bionic

# TODO: May be required for Travis on Windows
# filter_secrets: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
      - make
      - pkg-config
      - zip
      - g++
      - zlib1g-dev
      - unzip
      - python3

os:
  - linux
  - osx
  - windows

env:
  - BUCKAROO_VERSION=v2.2.0 PKG_CONFIG_PATH=/usr/lib/pkgconfig
  - BUCKAROO_VERSION=bazel-alpha-3 BUCKAROO_USE_BAZEL=1 PKG_CONFIG_PATH=/usr/lib/pkgconfig MSYS2_ARG_CONV_EXCL="//"

cache:
  directories:
    - $HOME/.buckaroo/cache
    - $TRAVIS_BUILD_DIR/bin

osx_image: xcode9.3

before_install:
  - travis_wait ./travis/before-install-$TRAVIS_OS_NAME.sh

script:
  - travis_wait ./travis/script.sh
